project:
  type: website

website:
  title: "DB Design"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: lecture2.qmd
        text: Lecture 2

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

